name = 'pkgr'
version = '0.1.1'
summary = "Package Linux pacakges"
author = "Dilawar Singh <dilawar.s.rajput@gmail.com>"
maintainer = "Dilawar Singh <dilawar.s.rajput@gmail.com>"
description = 'file://README.md'
license = 'GNUv3'
url = "https://github.com/dilawar/pkgr"
source = "file://.#pkgr-${version}.tar.gz"

[extra]
rpm = ['BuildArchitectures: noarch']

[builddeps]
# deb is default for all debian based distro
deb = ["python3-dev"]
# rpm is default for all rpm based distro
rpm = ["python3-devel"]
# OS spefic here.
fedora = ["python3-devel"]

[deps]
rpm=''
deb=''

[configure]
rpm = ''
deb = ''

[build]
rpm = '''
%py3_build
'''

[install]
rpm='''
%py3_install
'''

# files to install
[files]
rpm='''
/usr/bin/pkgr
%{python3_sitelib}/pkgr/
%ghost %{python3_sitelib}/*egg-info
'''

[changelog]
rpm='file://CHANGELOG.rpm.txt'
deb='file://CHANGELOG.deb.txt'
